//exception_handling
using System;
					
public class Program
{
	public static void Main()
	{
		int a=5;
		//int c=a/0;
		int[] arr = new int [2];
		try
		{
			Console.WriteLine(arr[2]);
		}
		catch
		{
			Console.WriteLine("some exception comes");
		}
		Console.ReadLine();
	}
}